import { Chord } from '../interfaces';

export const CHORDS: { [key: string]: Chord } = {
  C: { name: 'c', display: 'C', filename: 'c.mp3' },
  Cm: { name: 'cm', display: 'Cm', filename: 'cm.mp3' },
  C_E: { name: 'c_e', display: 'C/E', filename: 'c_e.mp3' },
  CS: { name: 'cs', display: 'C#', filename: 'cs.mp3' },
  CSm: { name: 'csm', display: 'C#m', filename: 'csm.mp3' },
  CS_F: { name: 'cs_f', display: 'C#/F', filename: 'cs_f.mp3' },
  D: { name: 'd', display: 'D', filename: 'd.mp3' },
  Dm: { name: 'dm', display: 'Dm', filename: 'dm.mp3' },
  D_FS: { name: 'd_fs', display: 'D/F#', filename: 'd_fs.mp3' },
  DS: { name: 'ds', display: 'D#', filename: 'ds.mp3' },
  DSm: { name: 'dsm', display: 'D#m', filename: 'dsm.mp3' },
  DS_G: { name: 'ds_g', display: 'D#/G', filename: 'ds_g.mp3' },
  E: { name: 'e', display: 'E', filename: 'e.mp3' },
  Em: { name: 'em', display: 'Em', filename: 'em.mp3' },
  E_GS: { name: 'e_gs', display: 'E/G#', filename: 'e_gs.mp3' },
  F: { name: 'f', display: 'F', filename: 'f.mp3' },
  Fm: { name: 'fm', display: 'Fm', filename: 'fm.mp3' },
  F_A: { name: 'f_a', display: 'F/A', filename: 'f_a.mp3' },
  FS: { name: 'fs', display: 'F#', filename: 'fs.mp3' },
  FSm: { name: 'fsm', display: 'F#m', filename: 'fsm.mp3' },
  FS_AS: { name: 'fs_as', display: 'F#/A#', filename: 'fs_as.mp3' },
  G: { name: 'g', display: 'G', filename: 'g.mp3' },
  Gm: { name: 'gm', display: 'Gm', filename: 'gm.mp3' },
  G_B: { name: 'g_b', display: 'G/B', filename: 'g_b.mp3' },
  GS: { name: 'gs', display: 'G#', filename: 'gs.mp3' },
  GSm: { name: 'gsm', display: 'G#m', filename: 'gsm.mp3' },
  GS_C: { name: 'gs_c', display: 'G#/C', filename: 'gs_c.mp3' },
  A: { name: 'a', display: 'A', filename: 'a.mp3' },
  Am: { name: 'am', display: 'Am', filename: 'am.mp3' },
  A_CS: { name: 'a_cs', display: 'A/C#', filename: 'a_cs.mp3' },
  AS: { name: 'as', display: 'A#', filename: 'as.mp3' },
  ASm: { name: 'asm', display: 'A#m', filename: 'asm.mp3' },
  AS_D: { name: 'as_d', display: 'A#/D', filename: 'as_d.mp3' },
  B: { name: 'b', display: 'B', filename: 'b.mp3' },
  Bm: { name: 'bm', display: 'Bm', filename: 'bm.mp3' },
  B_DS: { name: 'b_ds', display: 'B/D#', filename: 'b_ds.mp3' }
};
